// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.20.1
// source: github.com/bilbercode/protoc-gen-prokaf/test/proto/example.proto

package example

import (
	_ "github.com/bilbercode/protoc-gen-prokaf/prokaf"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TestOne struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id  string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Foo string `protobuf:"bytes,2,opt,name=foo,proto3" json:"foo,omitempty"`
}

func (x *TestOne) Reset() {
	*x = TestOne{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_bilbercode_protoc_gen_prokaf_test_proto_example_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestOne) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestOne) ProtoMessage() {}

func (x *TestOne) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_bilbercode_protoc_gen_prokaf_test_proto_example_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestOne.ProtoReflect.Descriptor instead.
func (*TestOne) Descriptor() ([]byte, []int) {
	return file_github_com_bilbercode_protoc_gen_prokaf_test_proto_example_proto_rawDescGZIP(), []int{0}
}

func (x *TestOne) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TestOne) GetFoo() string {
	if x != nil {
		return x.Foo
	}
	return ""
}

type TestTwo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
}

func (x *TestTwo) Reset() {
	*x = TestTwo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_bilbercode_protoc_gen_prokaf_test_proto_example_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestTwo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestTwo) ProtoMessage() {}

func (x *TestTwo) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_bilbercode_protoc_gen_prokaf_test_proto_example_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestTwo.ProtoReflect.Descriptor instead.
func (*TestTwo) Descriptor() ([]byte, []int) {
	return file_github_com_bilbercode_protoc_gen_prokaf_test_proto_example_proto_rawDescGZIP(), []int{1}
}

func (x *TestTwo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TestTwo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

var File_github_com_bilbercode_protoc_gen_prokaf_test_proto_example_proto protoreflect.FileDescriptor

var file_github_com_bilbercode_protoc_gen_prokaf_test_proto_example_proto_rawDesc = []byte{
	0x0a, 0x40, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x69, 0x6c,
	0x62, 0x65, 0x72, 0x63, 0x6f, 0x64, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2d, 0x67,
	0x65, 0x6e, 0x2d, 0x70, 0x72, 0x6f, 0x6b, 0x61, 0x66, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x07, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x1a, 0x34, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x69, 0x6c, 0x62, 0x65, 0x72, 0x63, 0x6f,
	0x64, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2d, 0x67, 0x65, 0x6e, 0x2d, 0x70, 0x72,
	0x6f, 0x6b, 0x61, 0x66, 0x2f, 0x70, 0x72, 0x6f, 0x6b, 0x61, 0x66, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x31, 0x0a, 0x07, 0x54, 0x65, 0x73, 0x74, 0x4f, 0x6e, 0x65, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03,
	0x66, 0x6f, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x66, 0x6f, 0x6f, 0x3a, 0x04,
	0xc8, 0xbb, 0x01, 0x01, 0x22, 0x3b, 0x0a, 0x07, 0x54, 0x65, 0x73, 0x74, 0x54, 0x77, 0x6f, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x3a, 0x04, 0xc8, 0xbb, 0x01,
	0x01, 0x42, 0x3a, 0x5a, 0x38, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x62, 0x69, 0x6c, 0x62, 0x65, 0x72, 0x63, 0x6f, 0x64, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x2d, 0x67, 0x65, 0x6e, 0x2d, 0x70, 0x72, 0x6f, 0x6b, 0x61, 0x66, 0x2f, 0x74, 0x65, 0x73,
	0x74, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_github_com_bilbercode_protoc_gen_prokaf_test_proto_example_proto_rawDescOnce sync.Once
	file_github_com_bilbercode_protoc_gen_prokaf_test_proto_example_proto_rawDescData = file_github_com_bilbercode_protoc_gen_prokaf_test_proto_example_proto_rawDesc
)

func file_github_com_bilbercode_protoc_gen_prokaf_test_proto_example_proto_rawDescGZIP() []byte {
	file_github_com_bilbercode_protoc_gen_prokaf_test_proto_example_proto_rawDescOnce.Do(func() {
		file_github_com_bilbercode_protoc_gen_prokaf_test_proto_example_proto_rawDescData = protoimpl.X.CompressGZIP(file_github_com_bilbercode_protoc_gen_prokaf_test_proto_example_proto_rawDescData)
	})
	return file_github_com_bilbercode_protoc_gen_prokaf_test_proto_example_proto_rawDescData
}

var file_github_com_bilbercode_protoc_gen_prokaf_test_proto_example_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_github_com_bilbercode_protoc_gen_prokaf_test_proto_example_proto_goTypes = []interface{}{
	(*TestOne)(nil), // 0: example.TestOne
	(*TestTwo)(nil), // 1: example.TestTwo
}
var file_github_com_bilbercode_protoc_gen_prokaf_test_proto_example_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_github_com_bilbercode_protoc_gen_prokaf_test_proto_example_proto_init() }
func file_github_com_bilbercode_protoc_gen_prokaf_test_proto_example_proto_init() {
	if File_github_com_bilbercode_protoc_gen_prokaf_test_proto_example_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_github_com_bilbercode_protoc_gen_prokaf_test_proto_example_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestOne); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_bilbercode_protoc_gen_prokaf_test_proto_example_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestTwo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_github_com_bilbercode_protoc_gen_prokaf_test_proto_example_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_github_com_bilbercode_protoc_gen_prokaf_test_proto_example_proto_goTypes,
		DependencyIndexes: file_github_com_bilbercode_protoc_gen_prokaf_test_proto_example_proto_depIdxs,
		MessageInfos:      file_github_com_bilbercode_protoc_gen_prokaf_test_proto_example_proto_msgTypes,
	}.Build()
	File_github_com_bilbercode_protoc_gen_prokaf_test_proto_example_proto = out.File
	file_github_com_bilbercode_protoc_gen_prokaf_test_proto_example_proto_rawDesc = nil
	file_github_com_bilbercode_protoc_gen_prokaf_test_proto_example_proto_goTypes = nil
	file_github_com_bilbercode_protoc_gen_prokaf_test_proto_example_proto_depIdxs = nil
}
